### ISSUE TITLE
NMTokens does not inherit from mixbox.entities.Entity

### ISSUE THREAD

**Issue by m-harptq** [mitre/stix-edh#1]
Hey there,

We are leveraging `stix_edh` within our STIX parsing solution, along with a number of other STIX libraries. We've come across a poor interaction between `stix_edh` and the `stixmarx` library when parsing a `xsi:type="edh2cyberMarkingAssert:ISAMarkingsAssertionType"` `<marking:Marking_Structure>` tag like the following:
```
<stix:Handling>
     <marking:Marking>
         <marking:Controlled_Structure>//node() | //@*</marking:Controlled_Structure>
         <marking:Marking_Structure xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" isam_version="2.0" most_restrictive="true" xsi:type="edh2cyberMarkingAssert:ISAMarkingsAssertionType">
              <edh2:AccessPrivilege>
                  <edh2:privilegeAction>ANONYMOUSACCESS</edh2:privilegeAction>
                  <edh2:privilegeScope>all</edh2:privilegeScope>
                  <edh2:ruleEffect>deny</edh2:ruleEffect>
               </edh2:AccessPrivilege>
         </marking:Marking_Structure>
     </marking:Marking>
</stix:Handling>
```
The error is specifically tied to this tag: `<edh2:privilegeScope>all</edh2:privilegeScope>`. When walking the package with `stixmarx`, each element is assumed to be a `mixbox.entities.Entity` with the `typed_fields_with_attrnames()` method. However, the `<edh2:privilegeScope>all</edh2:privilegeScope>` tag is transformed via `stix_edh` into a `NMTokens` object, which curiously does not inherit from `mixbox.entities.Entity` and thus raises an attribute error on `typed_fields_with_attrnames()`. 

This is easily worked around on our end by dynamically adding `mixbox.entities.Entity` to `NmTokens`' bases:
```
if Entity not in stix_edh.common.NMTokens.__bases__:
    stix_edh.common.NMTokens.__bases__ += Entity,
```
Filing this in order to see if `NMTokens` was purposefully designed to *not* conform to the `mixbox.entities.Entity` interface, or if this was a slight oversight.
Thanks!

**Comment by m-harptq** [comment]
This links with [this](https://github.com/mitre/stixmarx/issues/10) issue opened with `stixmarx`

**Comment by emmanvg** [comment]
@m-harptq, sorry for the late resolution of this issue. It required more changes than anticipated, a release will follow shortly for `stix-edh`. I would also suggest to update `stixmarx` to the latest version (1.0.5). You should be able to navigate the object model normally now and identify markings applied. Hope this helps!
